/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUnverifiedRouteImport } from './routes/admin/unverified'
import { Route as AdminReverifyRouteImport } from './routes/admin/reverify'
import { Route as AdminFacesRouteImport } from './routes/admin/faces'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedReverifyRouteImport } from './routes/_authenticated/reverify'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as ApiPublicWhitelistRecheckRouteImport } from './routes/api/public/whitelist-recheck'
import { Route as AdminUserUserIdRouteImport } from './routes/admin/user.$userId'
import { Route as AuthenticatedTaskSlotRouteImport } from './routes/_authenticated/task.$slot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnverifiedRoute = AdminUnverifiedRouteImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReverifyRoute = AdminReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacesRoute = AdminFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReverifyRoute = AuthenticatedReverifyRouteImport.update({
  id: '/reverify',
  path: '/reverify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWhitelistRecheckRoute =
  ApiPublicWhitelistRecheckRouteImport.update({
    id: '/api/public/whitelist-recheck',
    path: '/api/public/whitelist-recheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTaskSlotRoute = AuthenticatedTaskSlotRouteImport.update({
  id: '/task/$slot',
  path: '/task/$slot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/reverify': typeof AuthenticatedReverifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
  '/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/reverify': typeof AuthenticatedReverifyRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/faces': typeof AdminFacesRoute
  '/admin/reverify': typeof AdminReverifyRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/task/$slot': typeof AuthenticatedTaskSlotRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/public/whitelist-recheck': typeof ApiPublicWhitelistRecheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/home'
    | '/profile'
    | '/referral'
    | '/reverify'
    | '/wallet'
    | '/withdraw'
    | '/admin/faces'
    | '/admin/reverify'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/admin/'
    | '/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/whitelist-recheck'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/home'
    | '/profile'
    | '/referral'
    | '/reverify'
    | '/wallet'
    | '/withdraw'
    | '/admin/faces'
    | '/admin/reverify'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/admin'
    | '/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/whitelist-recheck'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/_authenticated/reverify'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/admin/faces'
    | '/admin/reverify'
    | '/admin/unverified'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/admin/'
    | '/_authenticated/task/$slot'
    | '/admin/user/$userId'
    | '/api/public/whitelist-recheck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ApiPublicWhitelistRecheckRoute: typeof ApiPublicWhitelistRecheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unverified': {
      id: '/admin/unverified'
      path: '/unverified'
      fullPath: '/admin/unverified'
      preLoaderRoute: typeof AdminUnverifiedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reverify': {
      id: '/admin/reverify'
      path: '/reverify'
      fullPath: '/admin/reverify'
      preLoaderRoute: typeof AdminReverifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faces': {
      id: '/admin/faces'
      path: '/faces'
      fullPath: '/admin/faces'
      preLoaderRoute: typeof AdminFacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reverify': {
      id: '/_authenticated/reverify'
      path: '/reverify'
      fullPath: '/reverify'
      preLoaderRoute: typeof AuthenticatedReverifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whitelist-recheck': {
      id: '/api/public/whitelist-recheck'
      path: '/api/public/whitelist-recheck'
      fullPath: '/api/public/whitelist-recheck'
      preLoaderRoute: typeof ApiPublicWhitelistRecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/task/$slot': {
      id: '/_authenticated/task/$slot'
      path: '/task/$slot'
      fullPath: '/task/$slot'
      preLoaderRoute: typeof AuthenticatedTaskSlotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedReverifyRoute: typeof AuthenticatedReverifyRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedTaskSlotRoute: typeof AuthenticatedTaskSlotRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedReverifyRoute: AuthenticatedReverifyRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedTaskSlotRoute: AuthenticatedTaskSlotRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminFacesRoute: typeof AdminFacesRoute
  AdminReverifyRoute: typeof AdminReverifyRoute
  AdminUnverifiedRoute: typeof AdminUnverifiedRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFacesRoute: AdminFacesRoute,
  AdminReverifyRoute: AdminReverifyRoute,
  AdminUnverifiedRoute: AdminUnverifiedRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ApiPublicWhitelistRecheckRoute: ApiPublicWhitelistRecheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
